### ISSUE TITLE
about your code

### ISSUE THREAD

**Issue by xautzhaozhe** [zephyrhours/Anomaly-Detection-for-Hyperspectral-Imagery-Based-on-the-Regularized-Subspace-Method-and-Collaborati#1]
Hello, thank you very much for sharing the code about hyperspectral anomaly detection, and would like to ask you a few questions.
1. In the local_rx algorithm, why did you not subtract the mean vector when calculating the Mahalanobis distance?
2. CRD and LRX algorithms fill the image with 0 or mirror image, does this have a big impact on the result? How other people deal with when do compare algorithm?

thamk you

**Comment by zephyrhours** [comment]
Thanks for your attention. Here is your reply:
1. the LRX  algorithm code comes from other's sharing, not written by me. I;ve thought about your question before. The essence of the two operations is the same. The difference is that some data sets have been de averaged before operation. I have tested two operations, and their results are within the error range. And this kind of operation is usually better than what you say. So in this paper, it is used as a comparison algorithm.
2. There are many methods of boundary filling, different people may use different filling algorithms in programming, which is why the results of this paper are different, but this reason is also reasonable. As far as I know, boundary filling algorithms include: random filling, zero value filling, mirror filling, etc.The results of different filling methods are different, which depends on your specific algorithm. 

I think you should read more papers. Some papers have discussed the differences of these filling algorithms. You can also program LRX algorithm to compare the differences between the two. RX and LRX algorithm are very simple algorithms, and programming is a necessary skill for scientific researchers.

**Comment by xautzhaozhe** [comment]
> Thanks for your attention. Here is your reply:
> 
> 1. the LRX  algorithm code comes from other's sharing, not written by me. I;ve thought about your question before. The essence of the two operations is the same. The difference is that some data sets have been de averaged before operation. I have tested two operations, and their results are within the error range. And this kind of operation is usually better than what you say. So in this paper, it is used as a comparison algorithm.
> 2. There are many methods of boundary filling, different people may use different filling algorithms in programming, which is why the results of this paper are different, but this reason is also reasonable. As far as I know, boundary filling algorithms include: random filling, zero value filling, mirror filling, etc.The results of different filling methods are different, which depends on your specific algorithm.
> 
> I think you should read more papers. Some papers have discussed the differences of these filling algorithms. You can also program LRX algorithm to compare the differences between the two. RX and LRX algorithm are very simple algorithms, and programming is a necessary skill for scientific researchers.

**Comment by xautzhaozhe** [comment]
> > Thanks for your attention. Here is your reply:
> > 
> > 1. the LRX  algorithm code comes from other's sharing, not written by me. I;ve thought about your question before. The essence of the two operations is the same. The difference is that some data sets have been de averaged before operation. I have tested two operations, and their results are within the error range. And this kind of operation is usually better than what you say. So in this paper, it is used as a comparison algorithm.
> > 2. There are many methods of boundary filling, different people may use different filling algorithms in programming, which is why the results of this paper are different, but this reason is also reasonable. As far as I know, boundary filling algorithms include: random filling, zero value filling, mirror filling, etc.The results of different filling methods are different, which depends on your specific algorithm.
> > 
> > I think you should read more papers. Some papers have discussed the differences of these filling algorithms. You can also program LRX algorithm to compare the differences between the two. RX and LRX algorithm are very simple algorithms, and programming is a necessary skill for scientific researchers.

thank you very much!
